[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.1", features = ["postgres"] }
dotenv = "0.11.0"
serde = { version = "1.0.203", features = ["derive"] }
